export const FileIconMap: Record<string, string> = {
  doc: 'doc',
  docx: 'doc',
  docm: 'doc',
  pdf: 'pdf',
  xls: 'excel',
  xlsx: 'excel',
  xlsm: 'excel',
  ppt: 'ppt',
  pptx: 'ppt',
  jpg: 'jpg',
  jpeg: 'jpg',
  png: 'png',
  txt: 'text',
  csv: 'excel',
  md: 'md',
  mdx: 'md',
  mp4: 'mp4',
  avi: 'avi',
  mkv: 'mkv',
  rmvb: 'rmvb',
  wav: 'wav',
};
